language: python
python:
  - "3.8"
  - "pypy"

install:
  - pip install -r requirements.txt

script:
  - pytest LeftOvr/htmlcss/tests/test_views.py
  - pytest LeftOvr/LeftOvr/test_HomePage_urls.py
