# Generated by Django 3.1.2 on 2020-10-15 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=250)),
                ('lastName', models.CharField(max_length=250)),
                ('idNum', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=500)),
                ('passWords', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealType', models.CharField(max_length=500)),
                ('mealAvail', models.IntegerField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busName', models.CharField(max_length=500)),
                ('busAddress', models.CharField(max_length=500)),
                ('einNum', models.IntegerField(max_length=9)),
                ('busEmail', models.CharField(max_length=750)),
                ('busPassWords', models.CharField(max_length=500)),
            ],
        ),
    ]
