# Generated by Django 3.1.2 on 2020-11-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlcss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermore',
            name='password',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
