# Generated by Django 3.1.2 on 2020-10-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlcss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='mealAvail',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='einNum',
            field=models.CharField(max_length=9),
        ),
    ]
