# Generated by Django 3.1.2 on 2020-11-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('htmlcss', '0002_customermore_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermore',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='restaurantmore',
            name='profile',
        ),
        migrations.AddField(
            model_name='customermore',
            name='hide_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customermore',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profile_pics/default_profile_pics', max_length=255, null=True, upload_to='images/profile_pics'),
        ),
        migrations.AddField(
            model_name='restaurantmore',
            name='hide_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurantmore',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profile_pics/default_profile_pics', max_length=255, null=True, upload_to='images/profile_pics'),
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
