# Generated by Django 3.1.2 on 2020-11-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlcss', '0002_auto_20201112_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='mealType',
            field=models.TextField(max_length=500),
        ),
    ]
