# Generated by Django 3.1.2 on 2020-11-19 23:55

from django.db import migrations, models
import htmlcss.models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlcss', '0003_auto_20201119_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(blank=True, default=htmlcss.models.default_profile_image, max_length=255, null=True, upload_to=htmlcss.models.profile_Image),
        ),
    ]
